# Generated by Django 4.1.4 on 2023-04-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_user_alter_task_description_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
