# Generated by Django 4.1.4 on 2023-04-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team_member',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='filter',
        ),
    ]
